name: CI/CD for main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test -- -u  # Tự động cập nhật snapshots

      - name: Build project
        run: npm run build

      - name: Create 404.html for SPA fallback
        run: |
          cp dist/index.html dist/404.html

      # CD step
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist